@{
    # Module manifest for module 'AuditModule'
    #
    # Generated by: abayoumy
    #
    RootModule = 'AuditModule.psm1'
    ModuleVersion = '1.0'
    CompatiblePSEditions = @('Desktop', 'Core')
    GUID = 'c5cc2acf-06ce-4f30-9901-a7dd5d476a13'
    Author = 'abayoumy@outlook.com'
    CompanyName = 'www.abayoumy.tech'
    Copyright = '(c) 2025 abayoumy. All rights reserved.'
    Description = 'This module contains commands for auditing NTLM and LDAP.'
    PowerShellVersion = '5.1'
    # Minimum version of the PowerShell engine required by this module.
    # DotNetFrameworkVersion = '4.7.2'
    # Minimum version of the .NET Framework required by this module.
    # CLRVersion = '4.0'
    # Minimum version of the common language runtime (CLR) required by this module.
    # ProcessorArchitecture = 'None'
    # Processor architecture that this module is built for.
    FunctionsToExport = @('Export-NTLMEvents', 'Export-LDAPEvents', 'Export-ADInfo' , 'Get-DCs' , 'Export-AdminUsers')
    # List of functions to export from this module.
    # CmdletsToExport = @()
    # List of cmdlets to export from this module.
    # VariablesToExport = @()
    # List of variables to export from this module.
    # AliasesToExport = @()
    # List of aliases to export from this module.
    # DscResourcesToExport = @()
    # List of DSC resources to export from this module.
    # ModuleList = @()
    # List of modules that this module requires.
    # NestedModules = @()
    # List of modules that are nested within this module.
    # RequiredAssemblies = @()
    # List of assemblies that this module requires.
    # FileList = @()
    # List of all files that are part of this module.
    # PrivateData = @()
    # A hash table containing private data about this module. This data is not available to users.
    # Tags = @()
    # Tags that are used to describe this module.
    # HelpInfoURI = ''
    # URI of the help information for this module.
    # DefaultCommandPrefix = ''
    # Default prefix for commands exported from this module. Overrides the built-in command prefix.
}
